#!/usr/bin/env python3
# utils/ablation_cwe_temperature.py

"""
Ablation Study: Temperature Scaling for CWE Classifier
=======================================================

Measures how softmax temperature affects the CWE SecBERT classifier's
ability to surface the correct label in top-1 / top-3 / recall@5.

Why temperature scaling?
  The 15-class softmax can be over-confident: top-1 ~0.40 dominates,
  but top-2 ~0.35 is also viable. Dividing logits by T > 1.0 smooths
  the distribution, making top-2/3 classes more likely to cross the
  min_threshold used in production (0.15).

Usage
-----
    python utils/ablation_cwe_temperature.py
    python utils/ablation_cwe_temperature.py --samples 200

Dataset priority
----------------
  1. data/training/cve_cwe_train.csv  (generated by build_training_data.py)
  2. data/cache/nvd/*.json            (NVD cache, fallback)

Output: Markdown table printed to stdout for thesis inclusion.

Academic reference
------------------
  Guo et al. (2017). On Calibration of Modern Neural Networks.
  ICML 2017. https://arxiv.org/abs/1706.04599
  (Temperature scaling is a post-hoc calibration method.)
"""

import argparse
import csv
import json
import random
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "backend"))

META_FILE   = ROOT / "models" / "bert_cwe_meta.json"
DATASET_CSV = ROOT / "data"   / "training" / "cve_cwe_train.csv"
CACHE_DIR   = ROOT / "data"   / "cache"    / "nvd"

TEMPERATURES = [1.0, 1.2, 1.5, 2.0, 2.5]
DEFAULT_N    = 100
SEED         = 42


# ── Data loading ───────────────────────────────────────────────────────────────

def load_model_classes() -> set[str]:
    with open(META_FILE) as f:
        meta = json.load(f)
    return set(meta["label2id"].keys())


def load_from_csv(path: Path, model_classes: set[str], n: int, seed: int) -> list[dict]:
    """Stratified sample from cve_cwe_train.csv (columns: description, cwe_ids)."""
    by_class: dict[str, list[dict]] = defaultdict(list)

    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            desc = (row.get("description") or "").strip()
            raw  = (row.get("cwe_ids") or row.get("cwe_id") or "").strip()
            primary = raw.split("|")[0].strip()
            if desc and primary in model_classes:
                by_class[primary].append({"text": desc, "true_cwe": primary})

    rng = random.Random(seed)
    per_class = max(1, n // max(len(by_class), 1))
    samples: list[dict] = []
    for items in by_class.values():
        rng.shuffle(items)
        samples.extend(items[:per_class])

    rng.shuffle(samples)
    return samples[:n]


def load_from_cache(cache_dir: Path, model_classes: set[str], n: int, seed: int) -> list[dict]:
    """Fallback: use NVD cache JSON files (have 'description' + 'weaknesses' fields)."""
    samples: list[dict] = []
    for fp in cache_dir.glob("*.json"):
        try:
            with open(fp) as f:
                cve = json.load(f)
            desc = (cve.get("description") or "").strip()
            ws   = cve.get("weaknesses") or []
            primary = ws[0].strip() if ws else ""
            if desc and primary in model_classes:
                samples.append({"text": desc, "true_cwe": primary})
        except Exception:
            continue

    rng = random.Random(seed)
    rng.shuffle(samples)
    return samples[:n]


# ── Evaluation ─────────────────────────────────────────────────────────────────

def evaluate(classifier, samples: list[dict], temperature: float) -> dict:
    top1 = top3 = r5 = 0
    n = len(samples)

    for s in samples:
        preds = classifier.predict(
            s["text"],
            top_k=5,
            temperature=temperature,
            min_threshold=0.0,   # no threshold during ablation — measure raw ranking
        )
        ids   = [p["cwe_id"] for p in preds]
        true  = s["true_cwe"]

        if ids and ids[0] == true:
            top1 += 1
        if true in ids[:3]:
            top3 += 1
        if true in ids[:5]:
            r5 += 1

    return {
        "top1_acc": round(top1 / n * 100, 2),
        "top3_acc": round(top3 / n * 100, 2),
        "recall_5": round(r5   / n * 100, 2),
    }


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Ablation: temperature scaling for CWE classifier"
    )
    parser.add_argument("--samples", type=int, default=DEFAULT_N,
                        help=f"Number of test samples (default: {DEFAULT_N})")
    parser.add_argument("--seed", type=int, default=SEED)
    args = parser.parse_args()

    print("=" * 60)
    print("  CWE TEMPERATURE SCALING — ABLATION STUDY")
    print("=" * 60)

    if not META_FILE.exists():
        print(f"[ERR] {META_FILE} not found. Train the model first:")
        print("      python utils/train_cwe_classifier.py")
        sys.exit(1)

    model_classes = load_model_classes()
    print(f"\nModel: SecBERT CWE classifier ({len(model_classes)} classes)")
    print(f"Classes: {', '.join(sorted(model_classes))}")

    # ── Load samples ──
    samples: list[dict] = []
    if DATASET_CSV.exists():
        print(f"\nLoading from {DATASET_CSV} ...")
        samples = load_from_csv(DATASET_CSV, model_classes, args.samples, args.seed)
    if not samples and CACHE_DIR.exists():
        print(f"Falling back to NVD cache ({CACHE_DIR}) ...")
        samples = load_from_cache(CACHE_DIR, model_classes, args.samples, args.seed)
    if not samples:
        print("[ERR] No test samples. Run build_training_data.py to generate the CSV.")
        sys.exit(1)

    print(f"Loaded {len(samples)} samples (seed={args.seed})")
    from collections import Counter
    dist = Counter(s["true_cwe"] for s in samples)
    for cwe in sorted(dist):
        print(f"  {cwe}: {dist[cwe]}")

    # ── Load classifier ──
    from cwe_predictor import get_cwe_classifier
    clf = get_cwe_classifier()
    if not clf.is_available():
        print("[ERR] CWE classifier not available.")
        print("      Train it first: python utils/train_cwe_classifier.py")
        sys.exit(1)

    # ── Run ablation ──
    print(f"\nRunning {len(TEMPERATURES)} temperature settings × {len(samples)} samples …\n")
    results: dict[float, dict] = {}
    for T in TEMPERATURES:
        print(f"  T={T:<4} …", end="", flush=True)
        results[T] = evaluate(clf, samples, T)
        m = results[T]
        print(f"  top-1={m['top1_acc']:5.2f}%  top-3={m['top3_acc']:5.2f}%  recall@5={m['recall_5']:5.2f}%")

    # ── Markdown table ──
    print("\n\n" + "=" * 60)
    print("  RESULTS (Markdown)")
    print("=" * 60)
    print(f"\n**Test samples:** {len(samples)}  ")
    print(f"**Model:** SecBERT fine-tuned CWE classifier (15 classes)  ")
    print(f"**Note:** min_threshold=0.0 during ablation (raw ranking)  \n")
    print("| Temperature | Top-1 Acc (%) | Top-3 Acc (%) | Recall@5 (%) |")
    print("|-------------|---------------|---------------|--------------|")
    for T in TEMPERATURES:
        m  = results[T]
        tag = " ← production" if T == 1.5 else ("  ← baseline" if T == 1.0 else "")
        print(
            f"| {T:<11} | {m['top1_acc']:>13.2f} | {m['top3_acc']:>13.2f} | {m['recall_5']:>12.2f} |{tag}"
        )

    best_t1 = max(TEMPERATURES, key=lambda t: results[t]["top1_acc"])
    best_r5 = max(TEMPERATURES, key=lambda t: results[t]["recall_5"])
    print(f"\n**Best Top-1:**    T={best_t1}  ({results[best_t1]['top1_acc']}%)")
    print(f"**Best Recall@5:** T={best_r5}  ({results[best_r5]['recall_5']}%)")

    delta_top1 = results[1.5]["top1_acc"] - results[1.0]["top1_acc"]
    delta_r5   = results[1.5]["recall_5"] - results[1.0]["recall_5"]
    print(f"\nT=1.5 vs T=1.0:")
    print(f"  Top-1 Δ = {delta_top1:+.2f}%")
    print(f"  Recall@5 Δ = {delta_r5:+.2f}%")
    print("\nInterpretation:")
    print("  T=1.0 → baseline (no scaling, hard argmax)")
    print("  T=1.5 → production default — smooths distribution so top-2/3 classes")
    print("          surface when top-1 confidence is marginal (~0.35–0.45 range)")
    print("  Expected: top-1 acc stays similar; top-3 / recall@5 improve")


if __name__ == "__main__":
    main()
